pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'DotnetBuild'
  variables:
    buildArgs: '-property:configuration=release'
    testArgs: '$(buildArgs) -f netcoreapp3.1'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Fody'
    inputs:
      command: 'build'
      projects: 'Fody.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Fody'
    enabled: false
    inputs:
      command: 'test'
      projects: 'Fody.sln'
      arguments: $(testArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Build Integration'
    inputs:
      command: 'build'
      projects: 'Integration\Integration.sln'
      arguments: $(buildArgs)
  - task: DotNetCoreCLI@2
    displayName: 'Test Integration'
    inputs:
      command: 'test'
      projects: 'Integration\Integration.sln'
      arguments: $(testArgs)


